language: go

go:
  - master

addons:
  ssh_known_hosts: overflod.chary.us

before_install:
  - openssl aes-256-cbc -K $encrypted_da0730754d12_key -iv $encrypted_da0730754d12_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

install:
  - ./scripts/install-hugo.sh

script:
  - hugo -b https://snoonet-beta.chary.us/

after_success:
  - ./scripts/deploy.sh