baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "Snoonet"
theme = "Snoonet"

summaryLength = 400

Paginate = 5

pluralizelisttitles = false

disablePathToLower = true

# https://gohugo.io/getting-started/configuration/#blackfriday-options
[blackfriday]
fractions = false

[params]
    webchatBaseURL = "https://webchat.snoonet.org/"
    redditBaseURL  = "https://reddit.com"

    [params.communityTypes]
        [[params.communityTypes.beauty_and_relationships]]
        Name = "Beauty and Relationships"

        [[params.communityTypes.gaming]]
        Name = "Gaming"

        [[params.communityTypes.health_and_food]]
        Name = "Health and Food"

        [[params.communityTypes.literature]]
        Name = "Literature"

        [[params.communityTypes.media]]
        Name = "Media"

        [[params.communityTypes.moderation_and_reddit]]
        Name = "Moderation and Reddit"

        [[params.communityTypes.music]]
        Name = "Music"

        [[params.communityTypes.news_and_politics]]
        Name = "News and Politics"

        [[params.communityTypes.occupations_and_education]]
        Name = "Occupations and Education"

        [[params.communityTypes.regional]]
        Name = "Regional"

        [[params.communityTypes.religion_and_lifestyle]]
        Name = "Religion and Lifestyle"

        [[params.communityTypes.social]]
        Name = "Social"

        [[params.communityTypes.sports]]
        Name = "Sports"

        [[params.communityTypes.technology_and_science]]
        Name = "Technology and Science"

[menu]
    [[menu.top]]
    identifier = "updates"
    name = "Updates"
    pre = ""
    url = "/"
    weight = -1000

    [[menu.top]]
    identifier = "webchat"
    name = "Webchat"
    pre = ""
    url = "https://webchat.snoonet.org/"
    weight = -990

    [[menu.main]]
    identifier = "updates"
    name = "Updates"
    pre = ""
    url = "/"
    weight = -1000

    [[menu.main]]
    identifier = "webchat"
    name = "Webchat"
    pre = ""
    url = "https://webchat.snoonet.org/"
    weight = -990

    [[menu.main]]
    identifier = "communities"
    name = "Communities"
    pre = ""
    url = "/community/"
    weight = -980

    [[menu.main]]
    identifier = "irc-servers"
    name = "IRC Servers"
    pre = ""
    url = "/irc-servers/"
    weight = -960

    [[menu.main]]
    identifier = "server-status"
    name = "Server Status"
    pre = ""
    url = "https://status.snoonet.org/"
    weight = -950

    [[menu.information]]
    identifier = "getting-started"
    name = "Getting Started"
    pre = ""
    url = "/help/"
    weight = -1000

    [[menu.information]]
    identifier = "mission-statement"
    name = "Mission Statement"
    pre = ""
    url = "/mission-statement/"
    weight = -990

    [[menu.information]]
    identifier = "why-snoonet"
    name = "Why Snoonet?"
    pre = ""
    url = "/why-snoonet/"
    weight = -980

    [[menu.information]]
    identifier = "staff"
    name = "Staff"
    pre = ""
    url = "/staff/"
    weight = -970

    [[menu.information]]
    identifier = "sponsors"
    name = "Sponsors"
    pre = ""
    url = "/sponsors/"
    weight = -960

    [[menu.information]]
    identifier = "support"
    name = "Support"
    pre = ""
    url = "https://support.snoonet.org/"
    weight = -950

    [[menu.rules]]
    identifier = "network-rules"
    name = "Network Rules"
    pre = ""
    url = "/rules/"
    weight = -1000

    [[menu.rules]]
    identifier = "help-guidelines"
    name = "Help and Guidelines"
    pre = ""
    url = "/help/"
    weight = -990

    [[menu.service]]
    identifier = "ssl"
    name = "SSL Fingerprints"
    pre = ""
    url = "/ssl/"
    weight = -1000

    [[menu.service]]
    identifier = "privacy"
    name = "Privacy and Security"
    pre = ""
    url = "/privacy/"
    weight = -990

    [[menu.service]]
    identifier = "tos"
    name = "Terms of Service"
    pre = ""
    url = "/tos/"
    weight = -980

    [[menu.service]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    pre = ""
    url = "/privacy-policy/"
    weight = -970
